language: go
services:
  - docker
go:
  - 1.12.x
script:
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .
  - docker build -t mydocker3013/goblog:$TRAVIS_COMMIT .
  - docker run -d mydocker3013/goblog:$TRAVIS_COMMIT
  - docker ps
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mydocker3013/goblog:$TRAVIS_COMMIT
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
env:
  global:
    secure: 3Eb2/w4ZVmSttGnokAtcSFTaoOZm1N618zb9AH5N/e7QTQ7mYfXIU28MYhBimYbGNQsLGWd7/GhpXhkfj+0aE2SbQoIPZOuuEMW91BNmh6ovM7hHUoICyy1L1tRW8tVpm26EdiPAeFKbWQboLsmlQSoJOiAL9ZL+t19khzF+h7xB+eFKkIEMOYCN+vUT/5M5cYIPInr5q1jqkDQA2mlFMAl3JuN+FSvfxdxaHV6zr4wCnK93wpLej4ngkHvPUORwLWfpUw6s5hlpiHxRyqBFZJLcwc2Xf5xPcrrRjJcKiAkvtOWv46ZK9LQPFW4c7696aegoQLzwXS66TGfgs/fEMB8pmBnbHH8auNVtTIErcXQ+lwRbmhSNHpKV/yGRgeTBwrOcGJZR5A9xQp84tqSK2kj5G+5YOjG20l75iSBzJtlIi09Yjy0dkdy7MFWL2WtyvJc/Y5bFp3qH/ffHETUChrwk8FOpfUetw5fecpAHs6TrizzVXkZ8f5xw2TkVUIDwEs2FnZblJjcdDoXAAdcwbcGTTQ3XN7HEoE2fqLKsiYku8DI4yaj0wvpB8rGx/WvnZhdXuT9+MmAEmLW9Cw9e4p8Zd307Ql9isglmqt+uDGOFWJi7H1O7U5YWp2s+yGVpzLXl0A16tPQDIBnEVIVaz23TUkDQ+Y2heE2MbeCxRfo=
before_install:
  - openssl aes-256-cbc -k "$super_secret_password" -in super_secret.txt.enc -out super_secret.txt -d
